#!/bin/bash
set -e

# Usage: ./scripts/deploy-to-netlify.sh [staging|production]

ENV=$1

if [[ "$ENV" == "production" ]]; then
  ENV_DIR="prod"
elif [[ "$ENV" == "prod" ]]; then
  ENV_DIR="prod"
elif [[ "$ENV" == "staging" ]]; then
  ENV_DIR="staging"
else
  echo "Usage: ./scripts/deploy-to-netlify.sh [staging|production]"
  exit 1
fi

SECRETS_DIR=".secrets/mypost/$ENV_DIR"

if [ ! -d "$SECRETS_DIR" ]; then
  echo "Error: Secrets directory not found at $SECRETS_DIR. Ensure submodules are initialized."
  exit 1
fi

# Check for netlify-cli
if ! command -v netlify &> /dev/null; then
    echo "netlify-cli could not be found. Please install it with: npm install -g netlify-cli"
    exit 1
fi

# Backup current .env.local if it exists
if [ -f .env.local ]; then
  echo "Backing up current .env.local to .env.local.bak..."
  mv .env.local .env.local.bak
fi

cleanup() {
  if [ -f .env.local.bak ]; then
    echo "Restoring .env.local from backup..."
    mv .env.local.bak .env.local
  else
    # If there was no backup, clean up the created .env.local
    rm -f .env.local
  fi
}
trap cleanup EXIT

echo "Preparing environment for $ENV..."

# Load NETLIFY_SITE_ID (and others) from netlify.env
if [ -f "$SECRETS_DIR/netlify.env" ]; then
  set -o allexport
  source "$SECRETS_DIR/netlify.env"
  set +o allexport
else
  echo "Warning: $SECRETS_DIR/netlify.env not found. NETLIFY_SITE_ID must be set manually."
fi

if [ -z "$NETLIFY_SITE_ID" ]; then
  echo "Error: NETLIFY_SITE_ID is not set. Check $SECRETS_DIR/netlify.env or set it manually."
  exit 1
fi

# Create new .env.local by concatenating secret env files
echo "# Generated by deploy-to-netlify.sh for $ENV deployment" > .env.local

# Helper to append file content if exists
append_env() {
  if [ -f "$1" ]; then
    echo "Loading $1..."
    cat "$1" >> .env.local
    echo "" >> .env.local # ensure newline
  fi
}

append_env "$SECRETS_DIR/.env"
append_env "$SECRETS_DIR/supabase.env"
append_env "$SECRETS_DIR/database.env"

echo "Environment prepared."

echo "Starting Netlify deployment for site ID: $NETLIFY_SITE_ID..."

# Run Netlify deploy
# Using --prod to deploy to the main branch of the site (staging or production site)
netlify deploy --build --prod --site "$NETLIFY_SITE_ID"

echo "Deployment finished successfully!"
